trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build'
      artifactName: 'drop'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '<din-azure-subscription>'
      appName: '<ditt-app-namn>'
      package: '$(Build.ArtifactStagingDirectory)/drop'
